spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:3307/tododb?severTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.dd-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=2b7d18036469062631e646fe6533cb2b
spring.jwt.expiration=900000